version: '3.7'

services:
  # MongoDB
  cadmus-biblio-mongo:
    image: mongo
    container_name: cadmus-biblio-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --logpath=/dev/null # --quiet
    ports:
      - 27017:27017
    networks:
      - cadmus-biblio-network

  # PostgreSQL
  cadmus-biblio-pgsql:
    image: postgres
    container_name: cadmus-biblio-pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - cadmus-biblio-network
    # volumes:
      # ensure you have created the var/db/pgsql folder in the host
      # https://hub.docker.com/r/postgis/postgis
      # - /var/db/pgsql:/var/lib/postgresql/data

  # Biblio API
  cadmus-biblio-api:
    image: vedph2020/cadmus_biblio_api:5.0.0
    container_name: cadmus-biblio-api
    ports:
      # https://stackoverflow.com/questions/48669548/why-does-aspnet-core-start-on-port-80-from-within-docker
      - 60058:80
    depends_on:
      - cadmus-biblio-mongo
      - cadmus-biblio-pgsql
    environment:
      # for Windows use : as separator, for non Windows use __
      # (see https://github.com/aspnet/Configuration/issues/469)
      - CONNECTIONSTRINGS__DEFAULT=mongodb://cadmus-biblio-mongo:27017/{0}
      - CONNECTIONSTRINGS__BIBLIO=Server=cadmus-biblio-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - SEED__BIBLIODELAY=25
      - SEED__ENTITYCOUNT=100
      - SERILOG__CONNECTIONSTRING=mongodb://cadmus-biblio-mongo:27017/{0}-log
      - STOCKUSERS__0__PASSWORD=P4ss-W0rd!
    networks:
      - cadmus-biblio-network

networks:
  cadmus-biblio-network:
    driver: bridge
