FROM mcr.microsoft.com/dotnet/aspnet:7.0.305-jammy-arm64v8 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0.305-jammy-arm64v8 AS build
WORKDIR /src
COPY ["CadmusBiblioApi/CadmusBiblioApi.csproj", "CadmusBiblioApi/"]
RUN dotnet restore "CadmusBiblioApi/CadmusBiblioApi.csproj" -s https://api.nuget.org/v3/index.json --verbosity d
COPY . .
RUN dotnet build "CadmusBiblioApi/CadmusBiblioApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CadmusBiblioApi/CadmusBiblioApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CadmusBiblioApi.dll"]
