<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<Authors>Daniele Fusi</Authors>
		<Company>Fusi</Company>
		<Product>Cadmus</Product>
		<Description>Cadmus bibliography API Entity Framework components</Description>
		<NeutralLanguage>en-US</NeutralLanguage>
		<PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
		<DebugType>portable</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<Deterministic>true</Deterministic>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Assets\cadmus-biblio.mysql" />
		<None Remove="Assets\cadmus-biblio.pgsql" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Assets\cadmus-biblio.mysql" />
		<EmbeddedResource Include="Assets\cadmus-biblio.pgsql" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="LinqKit.Core" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)'=='Debug'">
		<ProjectReference Include="..\Cadmus.Biblio.Core\Cadmus.Biblio.Core.csproj" />
	</ItemGroup>
	<ItemGroup Condition="'$(Configuration)'=='Release'">
		<PackageReference Include="Cadmus.Biblio.Core" />
	</ItemGroup>

</Project>
