<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<Authors>Daniele Fusi</Authors>
		<Company>Fusi</Company>
		<Product>Cadmus</Product>
		<Description>Cadmus bibliography mock data seeder.</Description>
		<Copyright>by Daniele Fusi 2021</Copyright>
		<NeutralLanguage>en-US</NeutralLanguage>
		<DebugType>portable</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<Deterministic>true</Deterministic>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Bogus" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)'=='Debug'">
		<ProjectReference Include="..\Cadmus.Biblio.Core\Cadmus.Biblio.Core.csproj" />
		<ProjectReference Include="..\Cadmus.Biblio.Ef\Cadmus.Biblio.Ef.csproj" />
	</ItemGroup>
	<ItemGroup Condition="'$(Configuration)'=='Release'">
		<PackageReference Include="Cadmus.Biblio.Core" />
		<PackageReference Include="Cadmus.Biblio.Ef" />
	</ItemGroup>

</Project>
